version: "3"
services:
  database:
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Wcs.37000
    expose:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql

  webserver:
    image: khaleddwm/k-group:v1.0
    ports:
      - "30500:80"
    volumes:
      - web_1:/var/www/k-group

volumes:
  db_data: {}
  web_1: {}