version: "3"
services:
  database:
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: k-groupe-web
    expose:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql

  webserver:
    image: khaleddwm/k-group:v1.12
    ports:
      - "80:80"
      - "443:443"

volumes:
  db_data: {}