version: "3"
services:
  database:
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: kg-dataweb
    expose:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql

  webserver:
    image: khaleddwm/k-group:v1.12
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - etc_data:/etc

volumes:
  db_data: {}
  etc_data: {}